### ISSUE TITLE
Transmedia Learning Framework for Python

### ISSUE THREAD

**Issue by elaineraybourn** [bssw-psip/ptc-catalog#1]
# Transmedia Learning Framework for Python

> TLF for Python
> Target: Learn Python enough to more efficiently recall functionality on demand.

# User Stories
> As a casual user of Python I want more Python tutorials and tips so that it becomes easier for me to recall functionality.

# Card(s)
> Variant A: How will I measure when I have achieved my desired result?
0. No Transmedia Learning Framework (TLF) for Python.
1. Watched Transmedia Learning tutorial, willing to use TLF to learn Python.
2. Developed Python TLF (see below) and using at least once a week.
3. Have completed 75% of TLF lesson suggestions.
4. Completed 100% of lessons in tutorial TLF for Python.
5. Continuing by curating new content to customize additional learning using the TLF.

Variant B: What are the steps (tasks) I need to accomplish to achieve my goal?

0. Agree to Use Transmedia Learning Framework (TLF) for python in tutorial (link).
1. Explore Python Video Webinar (link).
2. Study Website (link).
3. Sharpen skills with Python Quiz (link).
4. Master Python Commands with Flashcards for iOS (link).
5. Customize further learning with TLF process (link).

# Comments
> To complete the actions on this progress tracking card (PTC) please see https://ideas-productivity.org/events/hpc-best-practices-webinars/#webinar018

**Comment by jarrah42** [comment]
This has been added to the catalog.

**Comment by jarrah42** [comment]
Sorry, forgot to commit it. It's [here](https://github.com/bssw-psip/ptc-catalog/blob/master/catalog/TransmediaLearningForPython.md)
