### ISSUE TITLE
PTC Recommendation: Adopt A Git Workflow that Supports Testing and Peer-review

### ISSUE THREAD

**Issue by jarrah42** [bssw-psip/ptc-catalog#10]
# Adopt A Git Workflow that Supports Testing and Peer-review

**target**: Transition from a basic Git workflow to a collaborative workflow that supports testing and peer-review.

# User Stories

As a developer, I want to be able to transition from a basic Git work to a collaborative workflow 
so that all code changes are peer-reviewed and tested. 

# Card(s)

0. Project is using a basic Git workflow for pull-commit-push on a master branch.
1. Create local topic branches and confine work to those branches.
2. Use topic branches for collaboration by sharing branches via the main repository.
3. Create merge requests using Github/GitLab.
4. Set up automated testing of topic branches inside the merge request using Github/GitLab
5. Put reviews inside the merge request.

# Comments

- Automated testing: testing branches within Github/Gitlab in isolation
- Merge request also referred to as pull request
- Step 4 & 5 can be done in either order

**Comment by markcmiller86** [comment]
Steps 1-3 are all doable by standing up a local git repo without something like GitHub/GitLab. Its useful for teams to understand what GitHub/GitLab offer beyond basic git (1-3) is the web-based tools to manage distributed, collaborative development.

**Comment by markcmiller86** [comment]
Item 5 should be more like...Peer reviews are performed as part of a merge/pull request.

GitLab and BitBucket use *merge request* terminology whereas GitHub uses *pull request*. These are conceptually the same thing

**Comment by jarrah42** [comment]
> Steps 1-3 are all doable by standing up a local git repo without something like GitHub/GitLab. Its useful for teams to understand what GitHub/GitLab offer beyond basic git (1-3) is the web-based tools to manage distributed, collaborative development.

This could be added to the comments section

**Comment by jarrah42** [comment]
> Item 5 should be more like...Peer reviews are performed as part of a merge/pull request.

I'm fine with "Peer reviews are performed as part of a merge request". 

> 
> GitLab and BitBucket use _merge request_ terminology whereas GitHub uses _pull request_. These are conceptually the same thing

I think we should stick with one or the other, which is why I used merge in the text and added a comment that they both mean the same thing. Maybe that should be worded better?

**Comment by markcmiller86** [comment]
Yes, stick with *merge request*. But, give readers a note that its the same thing as a *pull request* somewhere in the comments.

**Comment by gonsie** [comment]
looks good to me. I think this is ready to be a PR.

**Comment by jarrah42** [comment]
PR created.
