### ISSUE TITLE
PTC Recommendation: Performance Regression Testing

### ISSUE THREAD

**Issue by rmmilewi** [bssw-psip/ptc-catalog#12]
# Performance Regression Testing

**Target**: To develop test suites that exercise performance capabilities and plans for how to make practical use of that performance data.

# User Stories

As a project lead, I want to be able to identify when changes to the code introduces performance issues so that we can address them sooner rather than later in the development process.

# Card(s)

0. No performance regression testing.
1. Define a primary use case for the software that can be exercised by tests.
2. Define a set of measurements that are important to performance for that use case and the granularity of those measurements. 
3. Create one or more test cases that exercise the performance capability according to the measurements.
4. Develop a means to track the performance history of this test over time.
5. Run performance tracking at regular intervals on relevant platforms and commit to reviewing that information as team.

# Comments

- Performance regression testing means knowing about the past, being able to run something fairly easily to check performance, to detect negative or positive changes. 
- Measurements can include wall clock time, resource utilization, cache performance, scalability, correctness, and others. The choice of measurements will inform the test(s) that need to be written.
- A performance test should be able to be checked relatively easily yet it is one that also exercises the code adequately.
- Bonus steps in this PTC might include repeating these steps to support a another use case, set of measurements, and/or more tests.

# Other Remarks

Contributed by David Bernholdt, Patricia Grubel, Benjamin Sims, and Reed Milewicz.

**Comment by jarrah42** [comment]
I think 1 & 2 are part of the same thing: "1. A testable primary use case and set of measurements that are important to performance are established.".

The other items then become:

2. One or more test cases that exercise the performance capability according to the measurements are created.
3. The performance history of the tests are tracked over time.
4. Performance tracking is run at regular intervals on relevant platforms.
5. Team commits to reviewing the performance tracking information.

**Comment by gonsie** [comment]
I agree with @jarrah42. I think this is ready to be PR'd.
