### ISSUE TITLE
PTC Recommendation: Offboarding-checklist

### ISSUE THREAD

**Issue by rinkug** [bssw-psip/ptc-catalog#16]
# Name and Description

> Suggest a short **name** that covers the topic of your card (like *UnitTesting*). 
> Then provide a brief description of the the goal (**target**) that a user is trying to reach with this card.

**Offboarding-checklist**: 

> Next, provide one or more **user stories** that explain the context of this goal.
> A user story is a statement that can be phrased as "As a _____, I want _____ so that _____."

**User Story**: As a project leader, I want to have a off-boarding checklist so that I can ensure that there is no loss of knowledge, work or equipment when a team member exits the team
## Card(s)

> Provide one or more cards to help a prospective user measure progress towards the goal (such as adopting a new practice or technology). A progress tracking card consists of a numbered list, where the numbers represent a set of scores (often from zero to five), and each item in the list is a qualitative description that illustrates what it means to reach that score. Zero should represent a starting state, and the highest number should represent fully achieving the goal.

0. No on-boarding checklist exists
1. Investigate what off-boarding checklists are used by similar contemporary projects in your organization or across-organizations of similar types.
2. Modify an existing checklist(s)/Create a new checklist(s) with a set of critical off-boarding tasks
3. Pilot test the checklist(s) as a pilot dry-run for your team with a set of employees. Obtain feedback
4. Re-discuss feedback with team and incorporate improvements and expand checklists
5. Evaluate process when a real team member exits

## Comments
> Here you may add any additional comments to help the reader use your item in the catalog, such as definitions or links to helpful material.
Please simplify the language

## Related Cards
> If you know of any existing cards which relate to this card (or would like to suggest cards that should be created), list them here.

This is similar to on boarding checklists: https://github.com/bssw-psip/ptc-catalog/issues/4

# Other Remarks

> If you have any other remarks or points of discussion that you want to raise in this GitHub Issue (e.g. "Is there a better way to phrase my user story?", feel free to those here.

**Comment by elaineraybourn** [comment]
Hi @rinkug I have assigned myself to help you generate a progress tracking card for this example. The steps you have listed above are tasks you would execute to put a checklist in place. A progress tracking card lists stages when you know that your progress at a certain stage is complete. Given the distinction, how would you reword the stages to reflect levels of completeness, versus tasks that should be executed to put the checklist in place?

**Comment by rinkug** [comment]
> Hi @rinkug I have assigned myself to help you generate a progress tracking card for this example. The steps you have listed above are tasks you would execute to put a checklist in place. A progress tracking card lists stages when you know that your progress at a certain stage is complete. Given the distinction, how would you reword the stages to reflect levels of completeness, versus tasks that should be executed to put the checklist in place?

I realize that one needs to put progress stages and not tasks. In my mind, I did envision these as stages. Here is another version of it.

0. No on-boarding checklist exists
1. A Investigate what off-boarding checklists are used by similar contemporary projects in your organization or across-organizations of similar types.
2. An initial checklist is documented (Modify an existing checklist(s)/Create a new checklist(s))
3. A pilot test dry-run of the checklist(s) is conducted within your team with a set of employees.
4. A pilot run, under supervision from a team member, is conducted when a new hire joins. 
5. Checklist is put into place for all future hires.

**Comment by elaineraybourn** [comment]
Hi Rinku, I've taken your tasks occurring at different stages, and added a sense for the team behaviors that would be present at each stage that signal a particular level of completeness. Feel free to modify if I have not captured your intent. Please submit a PR when you are happy with your PTC. Thank you for your effort.

   1. No on-boarding checklist exists
   2. Team has investigated off-boarding checklists in use by similar contemporary projects in  organization or across organizations of similar nature, and documented findings.
   3.  Team has adopted use of a checklist and executed successful pilot runs within team and with new hires. 
  4.  Team has documented checklist policy and achieved buy-in by all members.
  5.  Checklist in place for all future hires, and process is revised according to policy and needs.

**Comment by rinkug** [comment]
Revising text to  ensure that this is used when people exit the team. 

1. No off-boarding checklist exists
2. Team has investigated off-boarding checklists in use by similar contemporary projects in organization or across organizations of similar nature, and documented findings.
3. Team has adopted use of a checklist and executed successful pilot runs within team and with members departing team.
4. Team has documented checklist policy and achieved buy-in by all members.
5. Checklist in place for all future exiters, and process is revised according to policy and needs.

**Comment by elaineraybourn** [comment]
Looks good. I will review and create PR. Thanks for your effort.

**Comment by elaineraybourn** [comment]
PR created.
