### ISSUE TITLE
PTC: Improving project visibility to the community

### ISSUE THREAD

**Issue by rinkug** [bssw-psip/ptc-catalog#17]
# Name and Description

**Projectvisibility**: Improving project visibility to the community

**User Story**:
As a project lead, I want to increase my project visibility, so that my project has an increased chance of success.

## Card(s)

0. Project has no visibility
1. Work with team, research contemporary projects and create an "ideal plan" for project visibility
2. Creation of website, wiki, blogs and contact mailing lists within 3 months
3. Implement a plan to publicize work to research community through posters and publications within 12 months      
4. Implement social media presence within 12 months
5. Evaluate weakness and strengths after a year  and compare to ideal plan

**Comment by rinkug** [comment]
@jarrah42 : This is  a good topic for PTC but have I made the steps like a to-do list? How can they be improved?

**Comment by jarrah42** [comment]
I've created a pull request for a proposed PTC. Please continue discussion there.
