### ISSUE TITLE
PTC: Adopt Automated Correctness Testing in a Legacy Software Project

### ISSUE THREAD

**Issue by bartlettroscoe** [bssw-psip/ptc-catalog#25]
# Name and Description

**Name:** Adopt Automated Correctness Testing in a Legacy Software Project

**Target**: Adoption of automated testing for a [legacy software project](https://bssw.io/items/working-effectively-with-legacy-code) that has no automated tests at the beginning (e.g. where testing is done manually or only tested against customer codes).

**User Story**: As a developer on a legacy software project/product, I want my team to adopt increasing more rigorous and effective automated testing, so that development will be easier, users will see less defects, releases will go out faster, and the sustainability of my project will be improved.

For details, see PR #28 and the text in:

* https://github.com/bartlettroscoe/ptc-catalog/blob/25-adopt-auto-test-legacy-project/catalog/AdoptAutomatedCorrectnessTestingInLegacySoftwareProject.md

**Comment by bartlettroscoe** [comment]
@jarrah42, @gonsie, @rmmilewi, @markcmiller86,

Anyone willing to give the text in PR #28 a review?

**Comment by gonsie** [comment]
Work on this is being completed by #28
