### ISSUE TITLE
Label PTCs?

### ISSUE THREAD

**Issue by frobnitzem** [bssw-psip/ptc-catalog#41]
Investigate labeling PTCs by category and adding category information to the index. (Might be addressed by talking about metadata in #39)

**Comment by frobnitzem** [comment]
I think there should be a field for "tags" so that we can automatically generate lists of links.

**Comment by elaineraybourn** [comment]
I like this idea.

**Comment by mrmundt** [comment]
This topic has come back up again, and I'm working on it. We're going to start with a generic tag (`ecp-psip-ptc` or something of the like) so we can capture metrics for anyone who copy-pastes or downloads one of the cards and uses it in their repository. Later effort will be to add the specific categories.
