### ISSUE TITLE
Re-word user stories to use “we”

### ISSUE THREAD

**Issue by gonsie** [bssw-psip/ptc-catalog#5]
We should change the wording in our templates to use “we” instead of “I” in the users stories. This would make the team-perspective obvious from step 1.

Thoughts @rmmilewi and @jarrah42 (you two own the templates I think).

**Comment by jarrah42** [comment]
My understanding is that a "user story" in the agile sense, has a specific construction, which includes being written from the individual's perspective.

**Comment by elaineraybourn** [comment]
What is we reworded to I (we) .... so that I (we) .....? In the description of the user story construction we can indicate that users stories can be created by individuals, or by teams. Thoughts?

**Comment by jarrah42** [comment]
After discussion we decided to leave as "I" since this is used by agile, but to ensure that PTCs are team focussed.
