### ISSUE TITLE
PTC Recommendation Project Documentation 

### ISSUE THREAD

**Issue by gonsie** [bssw-psip/ptc-catalog#6]
Ideas suggested by @rinkug
> Starts with basic documentation: README
>  Ends with using automatic tools such as doxgen?

I’m going to split this into 2 cards based on the audience, users vs developers. Please share your thoughts!

- - - -

# Project Documentation

## Card 1: User Documentation

**As application developers, we want to document our project, so that new users will try the application.**

0. Little or no project documentation exists
1. A README, which provides basic installation instructions is written and added to the repository.
2. Possible technologies for creating user documentation are investigated and one (or more) is chosen by the team.
3. An initial set of user documentation is created and shared with the users.

### Comments
- Link to an article about possible user documentation tools: latex, readthedocs/sphinx, websites, wikis
- link to a PTC about engaging with users?
- probably needs a follow on PTC about keeping the user documentation up to date?

## Card 2: Developer Documentation

0. Little or no project documentation exists
1. A README and CONTRIBUTING guide are created, with basic information/policies for potential developers included.
2. Possible technologies for create developer documentation are investigated and one (or more) is chosen by the team.
3. A strategy for ensuring that new code and modifications to existing code are documented.

### Comments
- Link to an article about possible developer documentation tools: latex, readthedocs/sphinx, doxygen, websites, wikis

**Comment by jarrah42** [comment]
It seems like there could be some additional items. e.g. user feedback, documentation review, automatic generation of documentation, etc.

**Comment by rinkug** [comment]
Documentation for end-users  for a software project

0. Little or no project documentation exists
1. Investigate what documentation is provided by other contemporary similar projects. Inspired by research results, create a scope of your eventual ideal end-user documentation.
2. Focus on creation of initial set of documentation that is most likely to be used by end-users (ex: README, software introduction guide, software installation and initial setup testing guide, troubleshooting guide etc.)
3. Pilot phase to solicit feedback on the user documentation and incorporate improvements
4. Focus on simplifying documentation process through the use of auto-scripts or auto-documentation tools.
5. Focus on enhancing documentation to create your ideal end-user documentation

**Comment by rinkug** [comment]
Documentation for developers for a new software project

0. No project documentation exists
1. Investigate what documentation is provided by other contemporary similar projects. Inspired by research results, create a scope of your eventual ideal end-user documentation.
2. Focus on creation of initial set of documentation that is most likely to be used by team members for developer phase (ex: existing bug list, to-do list, brief design document, code-organization description, coding standard documentation)
3. Pilot phase to solicit feedback on the developer documentation and incorporate improvements. A fresh-eyes new team member perspective is desirable to understand what critical things are missing
4. Focus on simplifying documentation process through the use of auto-scripts or auto-documentation tools.
5. Focus on enhancing documentation to create your ideal end-user documentation
