### ISSUE TITLE
PTC Recommendation -- Issue Tracking 2

### ISSUE THREAD

**Issue by gonsie** [bssw-psip/ptc-catalog#9]
# Evaluate and Use an Issue Tracker

**Target**: Identify an issue tracking system which fits the team's needs.

**User Story**: As a software developer, I want to keep track of bugs and user feature requests so that I can keep track of and prioritize the work the team decides to tackle (or not).

## Card

0. No formal issue/bug/feature request tracker in place.
1.  A requirements list for the potential issue tracker has been created. Developer use cases / workflow have been identified and documented for potential issue tracker candidates at this stage. 
2. A list of potential issue tracking tools has been generated based on research and evaluation of features, cost, etc.*
3. Team has executed time-boxed plan and actively uses the issue tracking tool as per the plan in place on a trial basis.
4. Full adoption of issue tracking system by all members of team. Examples of adoption include active use of issue tracking tool to include the migration of existing bugs/feature requests and creation of new bugs/feature requests into the new system. 
5. Documentation developed by team on prioritization process and use of issue tracking tool so that new user request can be correctly created by new team members, etc. 

**Comment**: 
*The development team may decide that a formal issue tracker is not needed based on this research and evaluation.
- Common features of issue tracking systems: 
  - labeling the issues
  - visualizing the status of issues
  - statistics about the status of issues and how it changes over times
  - ability to assign issues to a particular person or team
  - integration with existing tools used by the team
  - ability to prioritize / schedule issues
  - notifications when issues are updated / resolved
  - ability for interested parties to comment on the issue

----

Thanks @prwolfe @jeanshuler for the help!

**Comment by elaineraybourn** [comment]
I rewrote the steps to reflect how the team would assess their progress toward their goal and what each stage of process improvement could yield.

**Comment by jarrah42** [comment]
Hi Elaine, before closing this one, you need to create a pull request. Go to the catalog directory and click on "Create new file". Name your file something like "EvaluateAndUseAnIssueTracker.md", then enter the content into the editor. Go down to the bottom and select "Create a new branch for this commit and start a pull request." Then click on "Propose new file". This will take you to a page to open a pull request. Enter "PTC: Evaluate and Use and Issue Tracker" for the title and put a reference to this issue in the comment (e.g. "PR created for issue #9". Assign a reviewer and set the projects to "PTC Review" (on the right hand side). Finally, click on "Create pull request". You can then close this issue.

**Comment by elaineraybourn** [comment]
Thank you! Let's include these instructions in our workflow documentation.
